version: "3.5"

volumes:

  data-varnish:
    driver: local

services:
  varnish:
    image: darioguarascio/varnish-elk-docker:latest

    volumes:
      - data-varnish:/vcache:rw
      # - ./config/varnish_backends.vcl:/usr/share/varnish/vcl/varnish_backends.vcl
    build:
      context: ./docker/varnish
      args:
        VARNISH_VERSION: ${VARNISH_VERSION:-6.5.2-r0}
    environment:
      ENV: ${ENV:-dev}
      VARNISHD_MEMORY: ${VARNISHD_MEMORY:-malloc,32m}
      VARNISH_PURGE_KEY: ${VARNISH_PURGE_KEY:-dev}
      VARNSIH_PROJECT_CODE: ${VARNISH_PROJECT_CODE:-}

    healthcheck:
      test: ["CMD", "sh", "-c", "test -e /proc/`cat /varnish.pid` || (kill -s 15 -1 && (sleep 10; kill -s 9 -1)) " ]
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 5s
    # logging:
    #   driver: syslog
    #   options:
    #     cache-disabled: "false"
    #     syslog-address: udp://${VARNISH_LOGGER_IP:-127.0.0.1}:${VARNISH_LOGGER_PORT:-5445}
    #     # syslog-format: "rfc3164"
    #     # tag: "node-red"
    restart: always
    ports:
      - ${VARNISH_LISTEN:-80}:80

